### ISSUE TITLE
set_timeout?

### ISSUE THREAD

**Issue by mattkrick** [smremde/node-lp_solve#10]
Any idea on why set_timeout isn't working? Things I tried: 
 - Uncommented out the code, rebuilt it with node-gyp
 - changed the source code so it would take an `int` instead of a `long`
 - changed the source code so the default `sectimeout` was 5 seconds

Nothing seemed to work.

**Comment by smremde** [comment]
I can't remember why that function was commented out.

I've pushed an uncommented version 4489155e4e80a79f28a80909a11a8420e46a93ad . Is that what yours looks like? If not could you test that? I have no LPs that take longer than a second to test at the moment. If you could add a test case that would be great.

**Comment by mattkrick** [comment]
Yep, I think I just assumed it wasn't working because `get_timeout` was returning undefined. Had to uncomment out 1 more line, but now it works, PR submitted.

**Comment by smremde** [comment]
`get_timeout` fixed in d7abeaad113ac7093c1aadc3f2589bf78ea34108. Thanks for spotting this.
