### ISSUE TITLE
Can node-lp_solve gets duals variables?

### ISSUE THREAD

**Issue by Blueswen** [smremde/node-lp_solve#12]
Hi, I am tying to do Data envelopment analysis(DEA) with node-lp_solve to solve linear programming problems. So far, I can get the correct solution and objectvalue, but I can't get duals variables (because DEA need them). So is there any possible I can get duals variables by some function?

**Comment by smremde** [comment]
Have you looked athttp://lpsolve.sourceforge.net/5.5/get_sensitivity_rhs.htm 

I've not got time to look at this today but that might point you in the right direction. Note any functions using **REAL have not yet been implemented.

**Comment by Blueswen** [comment]
Sorry for late reply, I found a method in lp_solve.h called get_var_dualresult. So I can get duals variables through this method.

```javascript
//brief code
var lp = new lpsolve.LinearProgram();
lp.lprec.get_var_dualresult(index_of_dualvar);
```
