### ISSUE TITLE
Fails to build with Node v10.2.1

### ISSUE THREAD

**Issue by maks-io** [smremde/node-lp_solve#17]
I don't know if this is still being maintained but I am currently on node v10.2.1 and installing this package with v0.2.13 fails with the following error:

> /home/maks/.node-gyp/10.2.1/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
>   318 |   declarator __attribute__((deprecated(message)))
>       |   ^~~~~~~~~~
> ../lp_solve.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE LinearProgram::print_debugdump(Nan::NAN_METHOD_ARGS_TYPE)’:
> ../lp_solve.cc:2206:40: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
>  2206 |  String::Utf8Value str_filename(info[0]);
>       |                                        ^
> In file included from /home/maks/.node-gyp/10.2.1/include/node/v8.h:26,
>                  from /home/maks/.node-gyp/10.2.1/include/node/node.h:63,
>                  from ../lp_solve.cc:1:
> /home/maks/.node-gyp/10.2.1/include/node/v8.h:2822:28: note: declared here
>  2822 |                   explicit Utf8Value(Local<v8::Value> obj));
>       |                            ^~~~~~~~~
> /home/maks/.node-gyp/10.2.1/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
>   318 |   declarator __attribute__((deprecated(message)))
>       |   ^~~~~~~~~~
> ../lp_solve.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE LinearProgram::get_nameindex(Nan::NAN_METHOD_ARGS_TYPE)’:
> ../lp_solve.cc:2597:39: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
>  2597 |  String::Utf8Value str_varname(info[0]);
>       |                                       ^
> In file included from /home/maks/.node-gyp/10.2.1/include/node/v8.h:26,
>                  from /home/maks/.node-gyp/10.2.1/include/node/node.h:63,
>                  from ../lp_solve.cc:1:
> /home/maks/.node-gyp/10.2.1/include/node/v8.h:2822:28: note: declared here
>  2822 |                   explicit Utf8Value(Local<v8::Value> obj));
>       |                            ^~~~~~~~~
> /home/maks/.node-gyp/10.2.1/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
>   318 |   declarator __attribute__((deprecated(message)))
>       |   ^~~~~~~~~~
> In file included from /home/maks/.node-gyp/10.2.1/include/node/node.h:63,
>                  from ../lp_solve.cc:1:
> /home/maks/.node-gyp/10.2.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
> /home/maks/.node-gyp/10.2.1/include/node/node_object_wrap.h:85:78:   required from here
> /home/maks/.node-gyp/10.2.1/include/node/v8.h:9238:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
>  9238 |                reinterpret_cast<Callback>(callback), type);
>       |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/maks/.node-gyp/10.2.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
> ../node_modules/nan/nan_object_wrap.h:66:61:   required from here
> /home/maks/.node-gyp/10.2.1/include/node/v8.h:9238:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
> make: *** [lp_solve.target.mk:106: Release/obj.target/lp_solve/lp_solve.o] Error 1
> make: Leaving directory '/mnt/data/coding/mw/node_modules/lp_solve/build'
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
> gyp ERR! System Linux 5.1.16-arch1-1-ARCH
> gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /mnt/data/coding/mw/node_modules/lp_solve
> gyp ERR! node -v v10.2.1
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok 
> npm WARN rollback Rolling back bindings@1.2.1 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/mnt/data/coding/mw/node_modules/lp_solve/node_modules/bindings'
> npm WARN rollback Rolling back nan@2.1.0 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/mnt/data/coding/mw/node_modules/lp_solve/node_modules/nan'
> npm WARN rollback Rolling back lp_solve@0.2.13 failed (this is probably harmless): ENOTEMPTY: directory not empty, rmdir '/mnt/data/coding/mw/node_modules/lp_solve/node_modules/bindings'
> npm WARN mw@1.0.0 No description
> npm WARN mw@1.0.0 No repository field.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! lp_solve@0.2.13 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the lp_solve@0.2.13 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/maks/.npm/_logs/2019-07-11T06_42_38_936Z-debug.log

**Comment by smremde** [comment]
Should be fix with https://github.com/smremde/node-lp_solve/pull/15 version and npm package 0.2.15
